# Session 09

[![Open and Execute in Google Colaboratory](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/astrojuanlu/ie-mbd-python-data-analysis-i/blob/main/sessions/Session%2009.ipynb)

- Tabular data with pandas DataFrames
- Slicing and indexing pandas DataFrames
- Filtering pandas DataFrames
- 1-dimensional data: pandas Series

## Tabular data with pandas `DataFrame`s

pandas is the most widely used Python library to read and manipulate tabular data. Its most important object is the `DataFrame`, which represents a rectangular table of rows and columns.

To start using pandas, you need to import it first. The most common way to import pandas is this:

In [ ]:
import pandas as pd

All the pandas functions will be accessible under the `pd` alias:

In [ ]:
pd.__version__

'2.2.2'

`DataFrame` objects are rectangular tables formed by a number of columns. Each column can have a different `dtype`, but all of them must have the same number of rows.

`DataFrame` objects can be created with the `DataFrame()` initializer, but in most cases they will appear as a result of other function or method calls, for example `pandas.read_csv`:

In [ ]:
df = pd.read_csv(
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/"
    "raw/main/data/titanic.csv"
)
# df = pd.read_csv("national_covid19.csv", index_col="date")  # You can specify the index column

It's a good practice to display the first few rows of the `DataFrame` right after opening it:

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Notice that you can retrieve the `dtypes` of the `DataFrame` (it's no longer a single `dtype`!) as well as a few other important properties:

--(important)Learn which are properties and which are methods

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

--(important) most of the time object tends to be string but it could also be different

In [ ]:
df.shape

(891, 12)

Some clarifications:

- The `object` dtype means something pandas couldn't parse. Could be a string, a string representing a date, or something completely different. In most cases it means `str`, but be careful when they appear.
- `float64` is similar to `int64`: a floating point value with 64 bits of precision.
- `NaN` means "Not a Number" and in general it means "missing value". In following sessions you will see how to effectively handle missing values, and what do they mean.

`DataFrame` objects have a large number of methods as well:

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

Notice that `object` columns are excluded. To include them all:

In [ ]:
df.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Dooley, Mr. Patrick",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

## Exercises

### 1. CSV reading

Read the `grandes-tenedores-madrid.csv` file and display
- number of rows,
- number of columns,
- dtypes of the columns,
- and the first five rows

Tip: The path is `https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/raw/main/data/grandes-tenedores-madrid.csv`

Data source: https://datos.civio.es/dataset/megatenedores-de-la-comunidad-de-madrid/

In [3]:
import pandas as pd
df_gtm = pd.read_csv("https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/raw/main/data/grandes-tenedores-madrid.csv")

In [ ]:
df_gtm.shape

(463, 19)

In [ ]:
nrows, ncols = df_gtm.shape
nrows

463

In [ ]:
df_gtm.head()

,NIF,Filial propietaria directa,Inmuebles,Matriz,Sede empresa matriz,Sociedad intermedia utilizada,Sede sociedad utilizada,Tipo sociedad utilizada,Administración,Sector,Subsector,Fuente,Fuente 2,Fuente 3,Fuente 4,Fuente 5,Fuente 6,Fuente 7,Fuente 8
0,A70302039,ABANCA CORPORACION BANCARIA SA,55,Abanca,España,Abanca,España,Empresa privada,NaN,Entidades financieras,Banca,https://civio.box.com/s/66p5k4lv0dr7ox37wzvnlk...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B09658576,"ACEF SPAIN PROPCO, S.L.U.",523,Axa,Francia,Acef Holding S.C.A,Luxemburgo,Socimi,NaN,Seguros,NaN,https://www.boe.es/borme/dias/2022/04/08/pdfs/...,https://www.boe.es/borme/dias/2022/04/07/pdfs/...,https://www.boe.es/borme/dias/2022/05/06/pdfs/...,NaN,NaN,NaN,NaN,NaN
2,B31813843,"ADANIA PATRIMONIO, S.L.",148,Adania,España,Adania,España,Empresa privada,NaN,Inmobiliaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Q2802152E,ADIF-ALTA VELOCIDAD,142,Adif,España,Adif,España,Empresas públicas o administraciones,Administración central,Otros,Infraestructuras aeroportuarias,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,B83195800,ADMAFINCAS S.L,88,Admafincas SL,España,Admafincas SL,España,Empresa privada,NaN,Inmobiliaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_gtm.describe()

          Inmuebles
count    463.000000
mean     256.714903
std     1110.339019
min       50.000000
25%       64.000000
50%       95.000000
75%      179.000000
max    21445.000000

In [ ]:
df_gtm.describe(include='all')

,NIF,Filial propietaria directa,Inmuebles,Matriz,Sede empresa matriz,Sociedad intermedia utilizada,Sede sociedad utilizada,Tipo sociedad utilizada,Administración,Sector,Subsector,Fuente,Fuente 2,Fuente 3,Fuente 4,Fuente 5,Fuente 6,Fuente 7,Fuente 8
count,463,463,463.000000,463,463,463,463,463,27,463,112,194,103,55,39,28,19,10,3
unique,463,463,NaN,373,13,400,12,9,4,11,24,169,88,45,33,22,15,7,3
top,E81064826,"ZAZO HERMANOS, C.B.",NaN,Blackstone,España,Spanish Residential (Reit) Holdco SARL,España,Empresa privada,Ayuntamiento,Inmobiliaria,Fondos de inversión,https://www.encajatualquiler.com/politica-de-p...,http://www.fidere-socimi.com/wp-content/upload...,https://civio.box.com/s/2kjbkbys11w115aqx2edz8...,https://civio.box.com/s/7qqjbmn1yc3o5d7r50kdn5...,https://civio.box.com/s/yr183xzwbr6fbydv9bl6qv...,https://civio.box.com/s/uotdgk9d65yeq8m365bix2...,https://civio.box.com/s/11pbtb9l0izi1dq11vujt4...,https://civio.box.com/s/11pbtb9l0izi1dq11vujt4...
freq,1,1,NaN,19,385,14,391,323,15,255,41,13,8,4,4,4,4,4,1
mean,NaN,NaN,256.714903,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,1110.339019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,50.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,64.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,95.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,179.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,21445.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_gtm.dtypes

NIF                              object
Filial propietaria directa       object
Inmuebles                         int64
Matriz                           object
Sede empresa matriz              object
Sociedad intermedia utilizada    object
Sede sociedad utilizada          object
Tipo sociedad utilizada          object
Administración                   object
Sector                           object
Subsector                        object
Fuente                           object
Fuente 2                         object
Fuente 3                         object
Fuente 4                         object
Fuente 5                         object
Fuente 6                         object
Fuente 7                         object
Fuente 8                         object
dtype: object

## Indexing

To extract a single column, use the indexing syntax, like you would do with a dictionary:

In [ ]:
df["Name"]

For anything else (retrieving a slice of columns, slicing both rows and columns), use the `.loc` accessor instead:

In [ ]:
df.loc[10:12,:] # with .loc , the end is included

In [ ]:
df.loc[10:12,"Name":"Age"]

                               Name     Sex   Age
10  Sandstrom, Miss. Marguerite Rut  female   4.0
11         Bonnell, Miss. Elizabeth  female  58.0
12   Saundercock, Mr. William Henry    male  20.0

In [ ]:
df.loc[10:12,["Name","Age","Embarked"]]

                               Name   Age Embarked
10  Sandstrom, Miss. Marguerite Rut   4.0        S
11         Bonnell, Miss. Elizabeth  58.0        S
12   Saundercock, Mr. William Henry  20.0        S

In [ ]:
df.loc[[10,12]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.70,G6,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.05,NaN,S

In [1]:
df.loc[10:12,"Age":"Name"] #important

NameError: name 'df' is not defined

In [ ]:
stats = df.describe()

In [ ]:
type(stats)

pandas.core.frame.DataFrame

In [ ]:
stats.loc["min":"max"]

     PassengerId  Survived  Pclass     Age  SibSp  Parch      Fare
min          1.0       0.0     1.0   0.420    0.0    0.0    0.0000
25%        223.5       0.0     2.0  20.125    0.0    0.0    7.9104
50%        446.0       0.0     3.0  28.000    0.0    0.0   14.4542
75%        668.5       1.0     3.0  38.000    1.0    0.0   31.0000
max        891.0       1.0     3.0  80.000    8.0    6.0  512.3292

In [ ]:
df.loc[df["Fare"] < 50]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df["Fare"] < 10 and df["Age"] > 30

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
(df["Fare"] < 10) & (df["Age"] > 30) #don't type "and" use its alternative bitwise operator

0      False
1      False
2      False
3      False
4       True
       ...
886    False
887    False
888    False
889    False
890     True
Length: 891, dtype: bool

In [ ]:
df.loc[:, "Age":]  # All rows, from the "Age" column to the last one

In [ ]:
df.loc[:5, ["SibSp", "Parch"]]  # Rows up to the one with the index 5 inclusive, columns "SibSp" and "Parch" only

In [ ]:
df.loc[
    [100, 110],  # Rows labeled 100 and 110
    ["Fare", "Cabin"]
]

Notice that these methods work for _any_ `DataFrame`. For example, the result of `.describe()` is _also_ a `DataFrame`!

In [ ]:
stats = df.describe()
stats

In [ ]:
type(stats)

In [ ]:
stats.loc["min":"max", ["Age", "Pclass"]]

## Selection

Filtering a `DataFrame` according to some condition is also done with the `.loc` accessor. For this, you can leverage the fact that operations between pandas `DataFrame` or `Series` objects and Python scalars are broadcasted automatically. In other words: operations are performed in sequence for all the elements of the pandas object.

In [ ]:
3 > 100  # Returns False

In [ ]:
df["Fare"] > 100  # Returns a Series of boolean values

Does the previous `Series` contain any `True` value? You can check with the `.any()` method:

In [ ]:
fare_filter = df["Fare"] > 100
fare_filter.any()

In [ ]:
fare_filter.dtype

You can use this filter or mask inside `.loc` to select a subset of rows:

In [ ]:
df.loc[fare_filter]

Combining filters requires some care, because the usual boolean Python operators don't work:

In [ ]:
(3 > 100) and (3 < 1_000)

In [ ]:
(df["Fare"] > 100) and (df["Fare"] < 1_000)  # Fails!

To operate boolean pandas `Series`, you need to use the bitwise operators:

- Bitwise OR `|`
- Bitwise AND `&`
- Bitwise NOT `~`

In [ ]:
# Select rows with cases_total between 100 and 1000
fare_filter = (100 < df["Fare"]) & (df["Fare"] < 1_000)
df.loc[fare_filter]

In [ ]:
# Select cases where "icu" is not null, equivalent to
# df.loc[df["icu"].notnull()]
df.loc[~df["Age"].isnull()]

## Exercises

### 2. Selecting rows and columns

From the `grandes-tenedores-madrid.csv` dataset, select the rows where the column "Inmuebles" is larger than 300 and "Subsector" is not "Fondos de inversión".

Then, keep only the columns "NIF", "Matriz", "Sede empresa matriz", and "Sector".

In [ ]:
df_gtm.loc[(df_gtm["Inmuebles"] > 300) & (df_gtm["Subsector"] != "Fondos de inversión"), ["NIF","Matriz","Sede empresa matriz", "Sector"]]

,NIF,Matriz,Sede empresa matriz,Sector
1,B09658576,Axa,Francia,Seguros
7,Q2801660H,Adif,España,Otros
8,A86212420,Aena,España,Otros
10,Q2840001h,Comunidad de Madrid,España,Parque público
11,A28221091,Agisa,España,Inmobiliaria
16,A87085445,Grupo Ortiz,España,Inmobiliaria
22,B81566366,Alquileres y Gestión SL,España,Inmobiliaria
28,A28100915,Banco Santander,España,Entidades financieras
34,B09658634,Axa,Francia,Seguros
41,G28239747,Guardia Civil,España,Otros
50,B84855329,Azata,España,Inmobiliaria
54,A08000143,Banco Sabadell,España,Entidades financieras
55,A39000013,Banco Santander,España,Entidades financieras
64,A63106157,CaixaBank,España,Entidades financieras
78,B86772837,Carrefour,Francia,Centros comerciales y mercados
112,A28121309,Construcciones residenciales y sociales,España,Inmobiliaria
120,A63379135,CaixaBank,España,Entidades financieras
146,A82044173,El Encinar del Norte SAU,España,Inmobiliaria
147,B28360543,El Parque Inmobiliario de Inversiones SL,España,Inmobiliaria
149,A82818311,Ayuntamiento de Alcobendas,España,Parque público
152,A83846139,Ayuntamiento de Rivas,España,Parque público
157,A28740314,Ayuntamiento de Madrid,España,Parque público
161,A87266359,SMT Europe Cooperatief UA,Países Bajos,Inmobiliaria
163,A28008647,España S.A. Compañía Nacional de Seguros,España,Seguros
222,B02826451,Grupo Promur 63 SL,España,Construcción
240,B63343172,CaixaBank,España,Entidades financieras
242,B67300533,CaixaBank,España,Entidades financieras
248,A28315034,Inmobiliaria Daganzo SA,España,Inmobiliaria
253,A28032852,"Inmobiliaria Hispana, SA",España,Inmobiliaria
256,A28254399,Grupo Lozoya,España,Inmobiliaria
257,A28316628,Blismuac SL,España,Inmobiliaria
260,B28079192,Inmobiliaria Sandi,España,Inmobiliaria
261,A28241610,Adenara SL,España,Inmobiliaria
295,A28323368,Groupe Générale Immobilière,Francia,Centros comerciales y mercados
301,A83787382,CBRE,Estados Unidos,Inmobiliaria
305,A58032244,CaixaBank,España,Entidades financieras
312,A81046039,Banco Santander,España,Entidades financieras
325,A86977790,Merlin Properties Socimi SA,España,Inmobiliaria
328,B84921758,Unicaja,España,Entidades financieras
335,B82153263,Negocios Brimaro SL,España,Inmobiliaria
346,A16004665,Obras y Vías SA,España,Construcción
348,R2800081H,Orden Hospitalaria de San Juan de Dios,España,Entidades religiosas
373,A28239523,Promociones Inmobiliarias Calero SL,España,Inmobiliaria
377,B86897865,Promociones Radente SL,España,Inmobiliaria
383,B87981999,Property Leases FTS Madrid,España,Inmobiliaria
395,B80677099,Rentur Patrimonial,España,Inmobiliaria
415,A86602158,Sareb,España,Entidades financieras
421,B66228768,Tauro Real Estate SL,España,Inmobiliaria
427,A78825734,"Terrenos, industrias y almacenes SA",España,Inmobiliaria
438,B86369915,Unibail-Rodamco-Westfiel SE,Francia,Centros comerciales y mercados
448,A87200598,Value Base LTD,Israel,Entidades financieras
456,B88391370,Renta Corporación,España,Inmobiliaria
457,A87805768,Renta Corporación,España,Inmobiliaria

## 1-dimensional data: pandas `Series`

Each of the columns of a `DataFrame` is a `Series` object. `Series` are mutable (hence you can add, remove, and replace elements) and homogeneous (all its elements must have the same type). As you will see, `Series` can be indexed by numerical position (like lists) or by label (like dictionaries).

For example, let's create a `Series` from a Python `list`:

In [ ]:
my_list = list(range(10, 15))
my_list

In [ ]:
ser = pd.Series(my_list)
ser

In [ ]:
type(ser)

`Series` have an important property, the `dtype`, that holds the type of its individual elements. As you can see in the string representation of the `Series`, the `dtype` of `ser` is `int64`, which means that `ser` is a `Series` of integers.

In [ ]:
ser.dtype

<div class="alert alert-info">The <code>64</code> part in <code>int64</code> alludes to how much memory does pandas use to store those integers, which is fixed to 64 bits. This means that, contrary to Python integers, there is a maximum integer pandas can store in an <code>int64</code>. But you don't need to worry about that now.</div>

If `pd.Series` receives heterogeneous input, it will cast everything to `object` and the `Series` will be less useful (no numerical operations will be allowed):

In [ ]:
pd.Series([True, True, False])  # dtype: bool

In [ ]:
pd.Series([True, True, False, 2])  # dtype: object

`Series` objects have a large number of methods, including some typical statistical and aggregation ones:

In [ ]:
ser.max(), ser.min()

In [ ]:
ser.mean(), ser.median(), ser.std()

And some more sophisticated methods:

In [ ]:
ser.describe()
# ser.describe([.33, .66, .99])  # notice that you can specify the percentiles!

Series made of non-numerical dtypes will have a different result for `.describe()`:

In [ ]:
pd.Series([1, 2, 2, 2, 3.0, "five"]).describe()

A `Series` has some `values` and an `index`. The `index` will become very important when working with `DataFrame`s.

In [ ]:
ser

In [ ]:
ser.values

In [ ]:
ser.index

`Series` objects can also be created from dictionaries, in which case the index will change:

In [ ]:
pd.Series({"a": 1, "b": 2})

You can refer to values by index using the `.loc` accessor:

In [ ]:
ser.loc[0]

<div class="alert alert-warning">Notice that we don't call <code>loc</code> a <em>method</em> because it is not called! It is a special object that "abuses" the indexing/slicing syntax. If you call it with parenthesis, you will get an error.</div>

The semantics of `.loc` with respect to slicing are slightly different from the base ones from Python. Most importantly, the end of the slice is included!

In [ ]:
ser.loc[1:3]

To access items by numerical position instead, use `.iloc`:

In [ ]:
ser2 = pd.Series({"a": 1, "b": 2})
ser2

In [ ]:
ser2.loc["a"]

In [ ]:
ser2.loc["b"]

In [ ]:
ser2.iloc[0]

In [ ]:
ser2.iloc[1]

## Exercises

### 3. Advanced: Managing semi-structured data

Load the `rick-and-morty.json` data to a Python object, then store the episodes list in a variable `episodes`, then pass it to the method `pandas.DataFrame.from_records` to turn the list of episodes into a `DataFrame`.

Then, answer the same questions from session 6, using exclusively pandas methods (no comprehensions or loops).

In [ ]:
import requests

DATA_URL = (
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/"
    "raw/main/data/rick-and-morty.json"
)

data = requests.get(DATA_URL).json()
print(type(data), len(data))

In [ ]:
df = pd.DataFrame.from_records(data["_embedded"]["episodes"])
df.head()