# Session 10

[![Open and Execute in Google Colaboratory](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/astrojuanlu/ie-mbd-python-data-analysis-i/blob/main/sessions/Session%2010.ipynb)

- Reading semi-structured data into pandas
- String methods on pandas columns
- The "group by and aggregate" operation
- The `agg` method

## Reading semi-structured data into pandas

pandas DataFrames are always table-like objects, but that doesn't mean that they're limited to CSV data. In fact, you can read many other formats using different `pandas.read_*` methods.

For example, it's possible to read semi-structured data into a pandas DataFrame. Let's do an example with JSON:

In [1]:
# BLUESKY_DATA_URL = "../data/bluesky_more_5000_likes_filtered.json"
BLUESKY_DATA_URL = (
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/"
    "raw/main/data/bluesky_more_5000_likes_filtered.json"
)

In [2]:
import pandas as pd

In [3]:
df = pd.read_json(BLUESKY_DATA_URL)
df.head(5)

,post_id,user_id,instance,date,text,langs,like_count,reply_count,repost_count,reply_to,replied_author,thread_root,thread_root_author,repost_from,reposted_author,quotes,quoted_author,labels,sent_label,sent_score
0,193115731,2648,ilovecitr.us,1976-05-31 15:05:10.052,Wins for Oppenheimer and Godzilla Minus One me...,[eng],6300,50,2138,NaN,NaN,NaN,NaN,65676,20990,NaN,NaN,NaN,2.0,0.807
1,193116187,2648,ilovecitr.us,1976-05-31 14:34:41.234,Today’s bake for brother’s 40th. I believe I h...,[eng],8266,171,1151,NaN,NaN,NaN,NaN,87314,46762,NaN,NaN,NaN,2.0,0.967
2,193116350,2648,ilovecitr.us,1976-05-31 14:31:01.544,Petition to honor Michael Shannon every Jan. 6,[eng],5327,87,1564,NaN,NaN,NaN,NaN,67433,78046,NaN,NaN,NaN,1.0,0.773
3,193116579,2648,ilovecitr.us,1976-05-30 13:35:00.156,Is it possible to fly a flag at twice-staff?,[eng],5566,55,1470,NaN,NaN,NaN,NaN,68732,64505,NaN,NaN,NaN,1.0,0.910
4,193116658,2648,ilovecitr.us,1976-05-30 13:33:00.024,1923: The world's richest man is an antisemite...,[eng],6719,87,2165,NaN,NaN,NaN,NaN,252171,33509,NaN,NaN,NaN,0.0,0.625

In [4]:
df.dtypes

post_id                        int64
user_id                        int64
instance                      object
date                  datetime64[ns]
text                          object
langs                         object
like_count                     int64
reply_count                    int64
repost_count                   int64
reply_to                     float64
replied_author               float64
thread_root                  float64
thread_root_author           float64
repost_from                    int64
reposted_author                int64
quotes                       float64
quoted_author                float64
labels                       float64
sent_label                   float64
sent_score                   float64
dtype: object

In [ ]:
df = pd.read_json(BLUESKY_DATA_URL)
df.head()

Notice several things:

(1) both the `text` and `langs` columns have dtype `object`, even though the former is made of strings and the latter is made of lists!

In [ ]:
df.dtypes

(2) If a given field is present in at least one record, the records that don't have it will hold a `NaN` value. You will learn more about handling missing data in the next session.

---

Alternatively, you could also read this data using the `requests` package into a native Python object:

In [5]:
# import json
import requests

# data = json.load(open(BLUESKY_DATA_URL))
data = requests.get(BLUESKY_DATA_URL).json()
type(data), len(data)

(list, 335)

And then use one of the `pandas.DataFrame.from_*` methods (notice that these are on a different namespace than the `pandas.read_*` methods):

In [ ]:
pd.DataFrame.from_records(data).head(2)

## Exercises

### 1. JSON reading

The `rick-and-morty.json` data is not so easy to read directly as JSON. Go ahead and try it. What's the error?

Use the alternative method: load the `rick-and-morty.json` data to a Python object, then store the episodes list in a variable `episodes`, then pass it to the method `pandas.DataFrame.from_records` to turn the list of episodes into a `DataFrame`.

List the first 5 rows to verify that it was correctly loaded. **Notice that some columns contain dictionaries**.

In [10]:
import requests

RICK_MORTY_DATA_URL = (
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/"
    "raw/main/data/rick-and-morty.json"
)

rm_data = requests.get(RICK_MORTY_DATA_URL).json()
print(type(rm_data), len(rm_data))

<class 'dict'> 24

In [7]:
df_rm = pd.read_json(RICK_MORTY_DATA_URL)

ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.

In [16]:
rm_data = requests.get(RICK_MORTY_DATA_URL).json()

In [17]:
rm_data

{'id': 216,
 'url': 'https://www.tvmaze.com/shows/216/rick-and-morty',
 'name': 'Rick and Morty',
 'type': 'Animation',
 'language': 'English',
 'genres': ['Comedy', 'Adventure', 'Science-Fiction'],
 'status': 'Running',
 'runtime': 30,
 'averageRuntime': 30,
 'premiered': '2013-12-02',
 'ended': None,
 'officialSite': 'http://www.adultswim.com/videos/rick-and-morty',
 'schedule': {'time': '23:00', 'days': ['Sunday']},
 'rating': {'average': 9},
 'weight': 99,
 'network': {'id': 10,
  'name': 'Adult Swim',
  'country': {'name': 'United States',
   'code': 'US',
   'timezone': 'America/New_York'}},
 'webChannel': None,
 'dvdCountry': None,
 'externals': {'tvrage': 33381, 'thetvdb': 275274, 'imdb': 'tt2861424'},
 'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
  'original': 'https://static.tvmaze.com/uploads/images/original_untouched/1/3603.jpg'},
 'summary': '<p>Rick is a mentally gifted, but sociopathic and alcoholic scientist and a grandfather to Morty; an awkward, impressionable, and somewhat spineless teenage boy. Rick moves into the family home of Morty, where he immediately becomes a bad influence.</p>',
 'updated': 1631872282,
 '_links': {'self': {'href': 'https://api.tvmaze.com/shows/216'},
  'previousepisode': {'href': 'https://api.tvmaze.com/episodes/2130800'}},
 '_embedded': {'episodes': [{'id': 14308,
    'url': 'https://www.tvmaze.com/episodes/14308/rick-and-morty-1x01-pilot',
    'name': 'Pilot',
    'season': 1,
    'number': 1,
    'type': 'regular',
    'airdate': '2013-12-02',
    'airtime': '22:30',
    'airstamp': '2013-12-03T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 8.6},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/292/730352.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/292/730352.jpg'},
    'summary': "<p>Rick takes Morty to another dimension to get some seeds for him but Morty's parents are considering to put Rick in a retirement home for keeping Morty away from school to help him in his lab.</p>",
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/14308'}}},
   {'id': 14309,
    'url': 'https://www.tvmaze.com/episodes/14309/rick-and-morty-1x02-lawnmower-dog',
    'name': 'Lawnmower Dog',
    'season': 1,
    'number': 2,
    'type': 'regular',
    'airdate': '2013-12-09',
    'airtime': '22:30',
    'airstamp': '2013-12-10T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 8.9},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/292/730780.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/292/730780.jpg'},
    'summary': "<p>Morty's small, white dog Snuffles gets on the nerves of the family, so Rick quickly builds a knowledge enhancing helmet for the dog. In the meantime, Rick and Morty decide to incept the dreams of Morty's math teacher, Mr. Goldenfold in order to convince him to give Morty A's in math. While the duo are sent on an epic dream world journey, Snuffles slowly gains sentience, which leads to a slew of even more problems.</p>",
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/14309'}}},
   {'id': 14310,
    'url': 'https://www.tvmaze.com/episodes/14310/rick-and-morty-1x03-anatomy-park',
    'name': 'Anatomy Park',
    'season': 1,
    'number': 3,
    'type': 'regular',
    'airdate': '2013-12-16',
    'airtime': '22:30',
    'airstamp': '2013-12-17T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/15/37914.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/15/37914.jpg'},
    'summary': "<p>It's around Christmas time and Jerry's parents are coming to visit so he wants everybody to have a normal holiday without technology and without Rick. Fortunately for him, Rick has other plans, involving building a molecular theme park inside of a friend of his named Ruben, and he shrinks down Morty and sends him in there to test it out.</p>",
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/14310'}}},
   {'id': 14311,
    'url': 'https://www.tvmaze.com/episodes/14311/rick-and-morty-1x04-m-night-shaym-aliens',
    'name': 'M. Night Shaym-Aliens!',
    'season': 1,
    'number': 4,
    'type': 'regular',
    'airdate': '2014-01-13',
    'airtime': '22:30',
    'airstamp': '2014-01-14T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/15/37915.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/15/37915.jpg'},
    'summary': '<p>Rick and Morty try to get to the bottom of a mystery in this M. Night Shyamalan style twistaroony of an episode.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/14311'}}},
   {'id': 14312,
    'url': 'https://www.tvmaze.com/episodes/14312/rick-and-morty-1x05-meeseeks-and-destroy',
    'name': 'Meeseeks and Destroy',
    'season': 1,
    'number': 5,
    'type': 'regular',
    'airdate': '2014-01-20',
    'airtime': '22:30',
    'airstamp': '2014-01-21T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/15/37916.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/15/37916.jpg'},
    'summary': '<p>Rick provides the family with a solution to their problems, freeing him up to go on an adventure led by Morty. Sounds good, better record this one, broh!</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/14312'}}},
   {'id': 14313,
    'url': 'https://www.tvmaze.com/episodes/14313/rick-and-morty-1x06-rick-potion-9',
    'name': 'Rick Potion #9',
    'season': 1,
    'number': 6,
    'type': 'regular',
    'airdate': '2014-01-27',
    'airtime': '22:30',
    'airstamp': '2014-01-28T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9.1},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/15/37917.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/15/37917.jpg'},
    'summary': "<p>Rick provides Morty with a love potion to get Jessica. The serum backfires &amp; Rick's attempt to fix things creates Cronenberg inspired monsters. Rick is okay with it but Morty feels partly responsible for creating a living nightmare.</p>",
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/14313'}}},
   {'id': 14314,
    'url': 'https://www.tvmaze.com/episodes/14314/rick-and-morty-1x07-raising-gazorpazorp',
    'name': 'Raising Gazorpazorp',
    'season': 1,
    'number': 7,
    'type': 'regular',
    'airdate': '2014-03-10',
    'airtime': '22:30',
    'airstamp': '2014-03-11T02:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 8.8},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/15/37918.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/15/37918.jpg'},
    'summary': '<p>Morty convinces Rick to buy him a sexy robot. Guess what tho? Trouble happens, dog.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/14314'}}},
   {'id': 14315,
    'url': 'https://www.tvmaze.com/episodes/14315/rick-and-morty-1x08-rixty-minutes',
    'name': 'Rixty Minutes',
    'season': 1,
    'number': 8,
    'type': 'regular',
    'airdate': '2014-03-17',
    'airtime': '22:30',
    'airstamp': '2014-03-18T02:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9.2},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/15/37919.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/15/37919.jpg'},
    'summary': "<p>When Rick hooks up the family's tv receiver with reality-tv shows from alternate dimensions, and allows them to see themselves in different versions of their lives, they begin to wonder what they have, and more importantly - what could have been.</p>",
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/14315'}}},
   {'id': 14316,
    'url': 'https://www.tvmaze.com/episodes/14316/rick-and-morty-1x09-something-ricked-this-way-comes',
    'name': 'Something Ricked This Way Comes',
    'season': 1,
    'number': 9,
    'type': 'regular',
    'airdate': '2014-03-24',
    'airtime': '22:30',
    'airstamp': '2014-03-25T02:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9.2},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/15/37920.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/15/37920.jpg'},
    'summary': '<p>Rick goes to battle with the devil, and Summer gets upset about it, broh. Plus Jerry and Morty hang out, broh!</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/14316'}}},
   {'id': 14317,
    'url': 'https://www.tvmaze.com/episodes/14317/rick-and-morty-1x10-close-rick-counters-of-the-rick-kind',
    'name': 'Close Rick-Counters of the Rick Kind',
    'season': 1,
    'number': 10,
    'type': 'regular',
    'airdate': '2014-04-07',
    'airtime': '22:30',
    'airstamp': '2014-04-08T02:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9.4},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/15/37921.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/15/37921.jpg'},
    'summary': '<p>Rick has a run in with some old associates, resulting in a fallout with Morty. You got any chips, broh?</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/14317'}}},
   {'id': 14318,
    'url': 'https://www.tvmaze.com/episodes/14318/rick-and-morty-1x11-ricksy-business',
    'name': 'Ricksy Business',
    'season': 1,
    'number': 11,
    'type': 'regular',
    'airdate': '2014-04-14',
    'airtime': '22:30',
    'airstamp': '2014-04-15T02:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 8.9},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/15/37922.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/15/37922.jpg'},
    'summary': "<p>Beth and Jerry head for an iceberg of a date leaving Rick in charge. Morty doesn't get to go on any more adventures if the house isn't in the same condition when they get back.</p>",
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/14318'}}},
   {'id': 157166,
    'url': 'https://www.tvmaze.com/episodes/157166/rick-and-morty-2x01-a-rickle-in-time',
    'name': 'A Rickle in Time',
    'season': 2,
    'number': 1,
    'type': 'regular',
    'airdate': '2015-07-26',
    'airtime': '23:30',
    'airstamp': '2015-07-27T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9.3},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/15/37923.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/15/37923.jpg'},
    'summary': '<p>Rick don goofed this time and mussed up the whole time frame broh! Beth and Jerry get romantic!</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/157166'}}},
   {'id': 183053,
    'url': 'https://www.tvmaze.com/episodes/183053/rick-and-morty-2x02-mortynight-run',
    'name': 'Mortynight Run',
    'season': 2,
    'number': 2,
    'type': 'regular',
    'airdate': '2015-08-02',
    'airtime': '23:30',
    'airstamp': '2015-08-03T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9.4},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/15/37924.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/15/37924.jpg'},
    'summary': '<p>Morty tries to save a life.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/183053'}}},
   {'id': 201178,
    'url': 'https://www.tvmaze.com/episodes/201178/rick-and-morty-2x03-auto-erotic-assimilation',
    'name': 'Auto Erotic Assimilation',
    'season': 2,
    'number': 3,
    'type': 'regular',
    'airdate': '2015-08-09',
    'airtime': '23:30',
    'airstamp': '2015-08-10T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9.2},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/15/37925.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/15/37925.jpg'},
    'summary': '<p>Rick becomes emotional; Beth and Jerry are hard on each other.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/201178'}}},
   {'id': 201179,
    'url': 'https://www.tvmaze.com/episodes/201179/rick-and-morty-2x04-total-rickall',
    'name': 'Total Rickall',
    'season': 2,
    'number': 4,
    'type': 'regular',
    'airdate': '2015-08-16',
    'airtime': '23:30',
    'airstamp': '2015-08-17T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9.6},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/15/38412.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/15/38412.jpg'},
    'summary': '<p>Meeting new friends; Morty goes ballistic.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/201179'}}},
   {'id': 201180,
    'url': 'https://www.tvmaze.com/episodes/201180/rick-and-morty-2x05-get-schwifty',
    'name': 'Get Schwifty',
    'season': 2,
    'number': 5,
    'type': 'regular',
    'airdate': '2015-08-23',
    'airtime': '23:30',
    'airstamp': '2015-08-24T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/15/39536.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/15/39536.jpg'},
    'summary': '<p>Rick and Morty must step up and save things; a new religion starts up.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/201180'}}},
   {'id': 201181,
    'url': 'https://www.tvmaze.com/episodes/201181/rick-and-morty-2x06-the-ricks-must-be-crazy',
    'name': 'The Ricks Must Be Crazy',
    'season': 2,
    'number': 6,
    'type': 'regular',
    'airdate': '2015-08-30',
    'airtime': '23:30',
    'airstamp': '2015-08-31T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9.5},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/68/171025.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/68/171025.jpg'},
    'summary': '<p>Rick forgets to check his oil, and must repair his car.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/201181'}}},
   {'id': 211831,
    'url': 'https://www.tvmaze.com/episodes/211831/rick-and-morty-2x07-big-trouble-in-little-sanchez',
    'name': 'Big Trouble in Little Sanchez',
    'season': 2,
    'number': 7,
    'type': 'regular',
    'airdate': '2015-09-13',
    'airtime': '23:30',
    'airstamp': '2015-09-14T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/18/46223.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/18/46223.jpg'},
    'summary': '<p>Rick joins in on hijinks, Beth and Jerry sort out relationship issues.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/211831'}}},
   {'id': 211832,
    'url': 'https://www.tvmaze.com/episodes/211832/rick-and-morty-2x08-interdimensional-cable-2-tempting-fate',
    'name': 'Interdimensional Cable 2: Tempting Fate',
    'season': 2,
    'number': 8,
    'type': 'regular',
    'airdate': '2015-09-20',
    'airtime': '23:30',
    'airstamp': '2015-09-21T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 8.5},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/68/171026.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/68/171026.jpg'},
    'summary': '<p>Jerry gets sick and Rick sparks up the TV.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/211832'}}},
   {'id': 211833,
    'url': 'https://www.tvmaze.com/episodes/211833/rick-and-morty-2x09-look-whos-purging-now',
    'name': "Look Who's Purging Now",
    'season': 2,
    'number': 9,
    'type': 'regular',
    'airdate': '2015-09-27',
    'airtime': '23:30',
    'airstamp': '2015-09-28T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9.3},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/300/751727.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/300/751727.jpg'},
    'summary': '<p>Morty makes a mistake and Jerry and Summer work on their father daughter relationship.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/211833'}}},
   {'id': 211834,
    'url': 'https://www.tvmaze.com/episodes/211834/rick-and-morty-2x10-the-wedding-squanchers',
    'name': 'The Wedding Squanchers',
    'season': 2,
    'number': 10,
    'type': 'regular',
    'airdate': '2015-10-04',
    'airtime': '23:30',
    'airstamp': '2015-10-05T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9.8},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/307/769086.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/307/769086.jpg'},
    'summary': '<p>Birdperson is getting married and invites the Smith family to the wedding.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/211834'}}},
   {'id': 1119144,
    'url': 'https://www.tvmaze.com/episodes/1119144/rick-and-morty-3x01-the-rickshank-rickdemption',
    'name': 'The Rickshank Rickdemption',
    'season': 3,
    'number': 1,
    'type': 'regular',
    'airdate': '2017-04-01',
    'airtime': '23:30',
    'airstamp': '2017-04-02T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 9.7},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/105/262759.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/105/262759.jpg'},
    'summary': '<p>Rick, still in galactic prison, puts an intricate escape plan into action. Back on Earth, which is now under federation control, Morty and Summer have an argument about their grandpa.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/1119144'}}},
   {'id': 1144079,
    'url': 'https://www.tvmaze.com/episodes/1144079/rick-and-morty-3x02-rickmancing-the-stone',
    'name': 'Rickmancing the Stone',
    'season': 3,
    'number': 2,
    'type': 'regular',
    'airdate': '2017-07-30',
    'airtime': '23:30',
    'airstamp': '2017-07-31T03:30:00+00:00',
    'runtime': 30,
    'rating': {'average': 8.8},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/122/306764.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/122/306764.jpg'},
    'summary': "<p>With the kids dealing with their parents' divorce, Rick takes them to a Mad Max-style universe where he tries to steal a green crystal from a group of scavengers.</p>",
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/1144079'}}},
   {'id': 1247370,
    'url': 'https://www.tvmaze.com/episodes/1247370/rick-and-morty-3x03-pickle-rick',
    'name': 'Pickle Rick',
    'season': 3,
    'number': 3,
    'type': 'regular',
    'airdate': '2017-08-06',
    'airtime': '23:30',
    'airstamp': '2017-08-07T03:30:00+00:00',
    'runtime': 24,
    'rating': {'average': 9.5},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/123/308859.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/123/308859.jpg'},

In [19]:
episodes = rm_data["_embedded"]["episodes"]
rm_df = pd.DataFrame.from_records(episodes)
rm_df.head(5)

,id,url,name,season,number,type,airdate,airtime,airstamp,runtime,rating,image,summary,_links
0,14308,https://www.tvmaze.com/episodes/14308/rick-and...,Pilot,1,1,regular,2013-12-02,22:30,2013-12-03T03:30:00+00:00,30,{'average': 8.6},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Rick takes Morty to another dimension to ge...,{'self': {'href': 'https://api.tvmaze.com/epis...
1,14309,https://www.tvmaze.com/episodes/14309/rick-and...,Lawnmower Dog,1,2,regular,2013-12-09,22:30,2013-12-10T03:30:00+00:00,30,{'average': 8.9},{'medium': 'https://static.tvmaze.com/uploads/...,"<p>Morty's small, white dog Snuffles gets on t...",{'self': {'href': 'https://api.tvmaze.com/epis...
2,14310,https://www.tvmaze.com/episodes/14310/rick-and...,Anatomy Park,1,3,regular,2013-12-16,22:30,2013-12-17T03:30:00+00:00,30,{'average': 9},{'medium': 'https://static.tvmaze.com/uploads/...,<p>It's around Christmas time and Jerry's pare...,{'self': {'href': 'https://api.tvmaze.com/epis...
3,14311,https://www.tvmaze.com/episodes/14311/rick-and...,M. Night Shaym-Aliens!,1,4,regular,2014-01-13,22:30,2014-01-14T03:30:00+00:00,30,{'average': 9},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Rick and Morty try to get to the bottom of ...,{'self': {'href': 'https://api.tvmaze.com/epis...
4,14312,https://www.tvmaze.com/episodes/14312/rick-and...,Meeseeks and Destroy,1,5,regular,2014-01-20,22:30,2014-01-21T03:30:00+00:00,30,{'average': 9},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Rick provides the family with a solution to...,{'self': {'href': 'https://api.tvmaze.com/epis...

In [ ]:
import pandas as pd

In [ ]:
rm_df = pd.DataFrame.from_records(data["_embedded"]["episodes"])
rm_df.head()

## The "group by and aggregate" operation

Group by operations in pandas are essential to perform advanced aggregations. The concept and the syntax are directly borrowed from SQL, and follow a similar "split-apply-combine" procedure. At a very high level, this is what happens:

![Group by and aggregate](../img/group-by-agg.png)

Group by operations are initiated by calling the `groupby` method of a DataFrame. But notice that this returns an intermediate object:

In [20]:
df.head(1)

,post_id,user_id,instance,date,text,langs,like_count,reply_count,repost_count,reply_to,replied_author,thread_root,thread_root_author,repost_from,reposted_author,quotes,quoted_author,labels,sent_label,sent_score
0,193115731,2648,ilovecitr.us,1976-05-31 15:05:10.052,Wins for Oppenheimer and Godzilla Minus One me...,[eng],6300,50,2138,NaN,NaN,NaN,NaN,65676,20990,NaN,NaN,NaN,2.0,0.807

In [21]:
df.groupby("instance")

To effectively use this object, you have to finalize the operation by calling an aggregation. The result will be another pandas object, with the index containing each of the distinct values of the column you are grouping by.

For example, to know how many posts are there per instance:

In [22]:
df.groupby("instance").size()

instance
bsky.social        305
com                  4
icopartners.com      3
ilovecitr.us         9
io                   1
net                 13
dtype: int64

And to extract the first (earliest) post of each instance:

In [ ]:
df.groupby("instance").first()

Some aggregations work with specific data types. For example, yhou might be interested in average statistics of some numerical columns:

In [ ]:
(
    df.loc[:, ["instance", "like_count", "reply_count"]]
    .groupby("instance")
    .mean()
)

## Exercises

### 2. Analyzing semi-structured data

Answer the remaining questions about the Rick & Morty data from session 6, using exclusively pandas methods (no comprehensions or loops).

## The `agg` method

Sometimes you want to apply more complex aggregations, or stack several of them, or apply different aggregations to different columns. The `.agg` method of the `DataFrameGroupBy` allows you to do all that.

In [ ]:
(
    df.loc[:, ["instance", "like_count", "reply_count"]]
    .groupby("instance")
    .agg(["mean", "std"])  # A list of aggregation functions
)

In [ ]:
(
    df.loc[:, ["instance", "like_count", "reply_count"]]
    .groupby("instance")
    .agg({"like_count": "mean", "reply_count": ["sum", "std"]})  # A dictionary/mapping of column names to aggregation functions
)

## Exercises

### 3. More analysis of semi-structured data

Load the Reddit data from Session 06 and answer the questions there, using exclusively pandas methods (no comprehensions or loops).

In [23]:
REDDIT_DATA_URL = (
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/"
    "raw/main/data/reddit_popular.json"
)