In [1]:
url = "https://raw.githubusercontent.com/Navenkumar-Balasubramaniam/00-General/refs/heads/main/07%20ML_1_practice/customer_membership_payment_spend_augmented.csv"

In [6]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [7]:
df = pd.read_csv(url)

In [8]:
df.head()

,Customer_ID,Membership_Type,Payment_Method,Monthly_Spend,Churn,Signup_Date,Last_Activity_Date,Region,Signup_Channel,Account_Notes,Spend_Bucket
0,C0001,Basic,PayPal,47.01,0,2023-07-11,2023-11-25,APAC,Web,Promo applied at checkout,Low
1,C0002,Gold,Credit Card,183.04,0,2023-03-22,2023-12-08,EMEA,Web,Discount expired this month,High
2,C0003,Silver,PayPal,108.76,0,2023-04-02,2024-10-15,AMER,Mobile,Promo applied at checkout,Medium
3,C0004,Gold,Credit Card,211.52,0,2023-12-04,2025-04-23,EMEA,Mobile,Discount expired this month,High
4,C0005,Platinum,Crypto,372.01,0,2023-09-27,2024-02-27,AMER,Web,Used referral code,High

In [9]:
categorical_list = ["Membership_Type","Payment_Method","Region","Signup_Channel","Spend_Bucket","Account_Notes"]
ohe = OneHotEncoder(drop = "first",sparse_output = False)
cat_arr = ohe.fit_transform(df.loc[:,categorical_list])

In [10]:
print(cat_arr)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]

In [12]:
ohe_columns = ohe.get_feature_names_out(categorical_list)

In [13]:
cat_df = pd.DataFrame(
    cat_arr,
    columns = ohe_columns,
    index = df.index
)

In [14]:
df_encoded = pd.concat(
    [df,cat_df],
    axis = 1
)

In [15]:
df_encoded.head()

,Customer_ID,Membership_Type,Payment_Method,Monthly_Spend,Churn,Signup_Date,Last_Activity_Date,Region,Signup_Channel,Account_Notes,...,Signup_Channel_Sales,Signup_Channel_Web,Spend_Bucket_Low,Spend_Bucket_Medium,Account_Notes_Discount expired this month,Account_Notes_No issues reported,Account_Notes_Promo applied at checkout,Account_Notes_Requested invoice via email,Account_Notes_Upgraded last quarter,Account_Notes_Used referral code
0,C0001,Basic,PayPal,47.01,0,2023-07-11,2023-11-25,APAC,Web,Promo applied at checkout,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,C0002,Gold,Credit Card,183.04,0,2023-03-22,2023-12-08,EMEA,Web,Discount expired this month,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,C0003,Silver,PayPal,108.76,0,2023-04-02,2024-10-15,AMER,Mobile,Promo applied at checkout,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,C0004,Gold,Credit Card,211.52,0,2023-12-04,2025-04-23,EMEA,Mobile,Discount expired this month,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,C0005,Platinum,Crypto,372.01,0,2023-09-27,2024-02-27,AMER,Web,Used referral code,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [16]:
df_encoded["Monthly_spend_avg"] = df.groupby("Payment_Method")["Monthly_Spend"].transform("mean")

In [17]:
df_encoded.head()

,Customer_ID,Membership_Type,Payment_Method,Monthly_Spend,Churn,Signup_Date,Last_Activity_Date,Region,Signup_Channel,Account_Notes,...,Signup_Channel_Web,Spend_Bucket_Low,Spend_Bucket_Medium,Account_Notes_Discount expired this month,Account_Notes_No issues reported,Account_Notes_Promo applied at checkout,Account_Notes_Requested invoice via email,Account_Notes_Upgraded last quarter,Account_Notes_Used referral code,Monthly_spend_avg
0,C0001,Basic,PayPal,47.01,0,2023-07-11,2023-11-25,APAC,Web,Promo applied at checkout,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,108.515000
1,C0002,Gold,Credit Card,183.04,0,2023-03-22,2023-12-08,EMEA,Web,Discount expired this month,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,94.319703
2,C0003,Silver,PayPal,108.76,0,2023-04-02,2024-10-15,AMER,Mobile,Promo applied at checkout,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,108.515000
3,C0004,Gold,Credit Card,211.52,0,2023-12-04,2025-04-23,EMEA,Mobile,Discount expired this month,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,94.319703
4,C0005,Platinum,Crypto,372.01,0,2023-09-27,2024-02-27,AMER,Web,Used referral code,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,303.346667